version: '3.8'
services:
  mcsv-training:
    container_name: mcsv-training
    image: maestros:1.0.1
    # build:
    #   context: ./
    #   dockerfile: ./eureka-server/Dockerfile
    ports:
      - '9002:9002'
    environment:
      #configuracion servers
      EUREKA_SERVER: "http://mcsv-eureka-server:8761/eureka"
      CONFIG_SERVER: "configserver:http://192.168.10.200:8888"
      JAVA_OPTS: "-Dspring.profiles.active=mcsv-developer"

      POSTGRES_PASSWORD: developer
      HOST_DB: 142.93.13.2
      PORT_DB: 5432
      DATABASE_NAME: 'db_training'
      SCHEMA_DB: 'data'    


    networks:
      - spring

    restart: always

networks:
  spring:
    external: true
    name: spring
